semantic_parser:
  model: "gpt-3.5-turbo-0125"
  temperature: 0.0
  max_tokens: 512
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0


response_generator:
  model: "gpt-3.5-turbo-0125"
  temperature: 0.0
  max_tokens: 512
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
